name = "jimmyverse-dev"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

pages_build_output_dir = "build/client"

[env.production]
name = "jimmyverse-dev"

[env.preview]
name = "jimmyverse-dev-preview"